using System;
using System.Reflection;
using System.Runtime.CompilerServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyTitleAttribute("NHibernate.Test")]
[assembly: AssemblyDescriptionAttribute("The Unit Tests for NHibernate.")]
[assembly: AssemblyCompanyAttribute("NHibernate.org")]
[assembly: AssemblyProductAttribute("NHibernate.Test")]
[assembly: AssemblyCopyrightAttribute("Licensed under LGPL.")]
[assembly: AssemblyVersionAttribute("4.0.0.4000")]
[assembly: AssemblyInformationalVersionAttribute("4.0.0.GA")]
[assembly: AssemblyFileVersionAttribute("4.0.0.4000")]
[assembly: AssemblyDelaySignAttribute(false)]

