using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyTitleAttribute("NHibernate")]
[assembly: AssemblyDescriptionAttribute("An object persistence library for relational databases.")]
[assembly: AssemblyCompanyAttribute("NHibernate.org")]
[assembly: AssemblyProductAttribute("NHibernate")]
[assembly: AssemblyCopyrightAttribute("Licensed under LGPL.")]
[assembly: AssemblyVersionAttribute("4.0.0.4000")]
[assembly: AssemblyInformationalVersionAttribute("4.0.0.GA")]
[assembly: AssemblyFileVersionAttribute("4.0.0.4000")]
[assembly: AssemblyDelaySignAttribute(false)]
[assembly: AllowPartiallyTrustedCallersAttribute()]
[assembly: SecurityRulesAttribute(SecurityRuleSet.Level1)]

